export const BurnaBoyProfile = {
    "data":{
       "artist":{
          "id":"3wcj11K77LjEY1PkEazffa",
          "uri":"spotify:artist:3wcj11K77LjEY1PkEazffa",
          "following":false,
          "sharingInfo":{
             "shareUrl":"https://open.spotify.com/artist/3wcj11K77LjEY1PkEazffa?si=gzBVnmusSb2anJddpgm0Jw",
             "shareId":"gzBVnmusSb2anJddpgm0Jw"
          },
          "profile":{
             "name":"Burna Boy",
             "verified":true,
             "pinnedItem":null,
             "biography":{
                "text":"With his fusion of dancehall, reggae, Afro-beat, and pop, Burna Boy emerged in the early part of the 2010s as one of Nigeria's fastest-rising stars. The LeriQ-produced 2012 single \"Like to Party\" proved to be his breakout track and paved the way for his full-length debut, L.I.F.E, a year later. Over the next five years, Burna released two more albums and collaborated with a variety of artists, from <a href=\"spotify:artist:2a0uxJgbvvIRI4GX8pYfcr\">J Hus</a> and Skales to <a href=\"spotify:artist:4UXqAaa6dQYAk18Lv7PEgX\">Fall Out Boy</a> and Lilly Allen. His international exposure widened with 2018's Outside, which hit number three on the Billboard Reggae chart and won the Nigeria Entertainment Award for Album of the Year. In advance of his next LP, 2019's African Giant, Burna made his first appearance at California's Coachella festival. \r\n\nBurna Boy was born Damini Ogulu in Lagos in 1991. He began making music at just ten years old when a fellow classmate at school gave him a copy of the production software FruityLoops. Armed with these means, he began to create his own beats on an old computer. After he graduated, he moved to London to attend university, but he dropped out after two years and moved back to Nigeria. In 2010, the 19-year-old Ogulu traveled to Nigeria's southern coast, where a mutual acquaintance, producer LeriQ, had some studio space. This marked a period when he began to connect to the music of his native country, having spent most of his youth immersed in American acts like <a href=\"spotify:artist:1HwM5zlC5qNWhJtM00yXzG\">DMX</a>. He delved into the dancehall and reggae music his father listened to, and explored the Afro-beat music preferred by his grandfather (who had also been <a href=\"spotify:artist:5CG9X521RDFWCuAhlo6QoR\">Fela Kuti</a>'s first manager). As a result of his new discoveries, Ogulu created a confluence of genres that would become his signature sound. \r\n\nWith production by LeriQ, Burna Boy created \"Like to Party,\" which marked his rise to prominence and generated a local buzz along the way. 2013 saw the release of his debut studio album; featuring guest slots from <a href=\"spotify:artist:3tVQdUvClmAT7URs9V3rsp\">Wizkid</a>, <a href=\"spotify:artist:7gEgjd9W1P1iAD9FbubrqC\">Timaya</a>, 2face, and M.I., L.I.F.E drew favorable reviews from the music press. For his sophomore effort, 2015's On a Spaceship, Burna parted ways with both his record company and LeriQ, and delivered a record even more diverse than his first. In 2017, he teamed up with producer <a href=\"spotify:artist:7BIkk865pwBrSZetA8Izic\">Juls</a> for the single \"Rock Your Body.\" A host of singles followed throughout the year, including \"GBA,\" \"Streets of Africa,\" \"Koni Baje,\" and \"Sekkle Down,\" featuring <a href=\"spotify:artist:2a0uxJgbvvIRI4GX8pYfcr\">J Hus</a>. After releasing the <a href=\"spotify:artist:13saZpZnCDWOI9D4IJhp1f\">Lily Allen</a>-aided single \"Heaven's Gate\" in early January 2018, Burna delivered his third album, Outside, later that month. \r\n\nHe returned a year later with the single \"Killin Dem,\" a collaboration with Zlatan. Along with additional singles like \"Dangote\" and \"On the Low,\" it was later included on his fourth album, African Giant, which saw release in July 2019. The LP was nominated in the Best World Music Album category of the 62nd Grammy Awards. In August 2020, Burna issued the full-length Twice as Tall, which included the single \"Wonderful.\" Featured on the album were guest appearances by <a href=\"spotify:artist:77zlytAFjPFjUKda8TNIDY\">Youssou N'Dour</a>, <a href=\"spotify:artist:4Otx4bRLSfpah5kX8hdgDC\">Naughty by Nature</a>, <a href=\"spotify:artist:4gzpq5DPGxSnKTe4SA8HAU\">Coldplay</a>'s <a href=\"spotify:artist:0LQoZQIV0mIs0y0XQb0Sw2\">Chris Martin</a>, and others. ~ Bekki Bemrose, Rovi"
             },
             "externalLinks":{
                "items":[
                   {
                      "name":"FACEBOOK",
                      "url":"https://facebook.com/Officialburnaboy"
                   },
                   {
                      "name":"INSTAGRAM",
                      "url":"https://instagram.com/burnaboygram"
                   },
                   {
                      "name":"TWITTER",
                      "url":"https://twitter.com/burnaboy"
                   },
                   {
                      "name":"WIKIPEDIA",
                      "url":"https://en.wikipedia.org/wiki/Burna_Boy"
                   }
                ]
             }
          },
          "visuals":{
             "gallery":{
                "items":[
                   {
                      "sources":[
                         {
                            "url":"https://i.scdn.co/image/7769b2106b9a2f210be07ef516e72ce08bf53454",
                            "width":640,
                            "height":640
                         }
                      ]
                   },
                   {
                      "sources":[
                         {
                            "url":"https://i.scdn.co/image/a5a621a8e7c03876cfe116120cffc8e4a9ee17b2",
                            "width":640,
                            "height":640
                         }
                      ]
                   },
                   {
                      "sources":[
                         {
                            "url":"https://i.scdn.co/image/c8373e559c3ee6f765ad0d9499d8cb0b34b04a4a",
                            "width":640,
                            "height":640
                         }
                      ]
                   }
                ]
             },
             "avatarImage":{
                "sources":[
                   {
                      "url":"https://i.scdn.co/image/17755d54631ecbc0c40d327738bcfc5287dd9aff",
                      "width":640,
                      "height":640
                   }
                ]
             },
             "headerImage":{
                "sources":[
                   {
                      "url":"https://i.scdn.co/image/ad1f4e7660896b0a87f886d6728027b85fa9f2e1",
                      "width":2660,
                      "height":1140
                   }
                ]
             }
          }
       }
    }
 }