export const DrakeProfile = {
    "data":{
       "artist":{
          "id":"3TVXtAsR1Inumwj472S9r4",
          "uri":"spotify:artist:3TVXtAsR1Inumwj472S9r4",
          "following":false,
          "sharingInfo":{
             "shareUrl":"https://open.spotify.com/artist/3TVXtAsR1Inumwj472S9r4?si=lJK0U8ZRQCm3b-5ESFiQjg",
             "shareId":"lJK0U8ZRQCm3b-5ESFiQjg"
          },
          "profile":{
             "name":"Drake",
             "verified":true,
             "pinnedItem":{
                "comment":"You’re Mines Still",
                "type":"PLAYLIST",
                "item":{
                   "uri":"spotify:user:drake:playlist:0GsvYNj45QjR245EWqgfDs",
                   "name":"OVO Sound ",
                   "images":{
                      "items":[
                         {
                            "sources":[
                               {
                                  "url":"https://i.scdn.co/image/ab67706c0000da84bdfa47802c4849d2aaf7db3e",
                                  "width":640,
                                  "height":640
                               }
                            ]
                         }
                      ]
                   }
                }
             },
             "biography":{
                "text":"Canadian rapper and vocalist Drake sustained a high-level commercial presence shortly after he hit the scene in 2006, whether with his own chart-topping releases or a long string of guest appearances on hits by the likes of <a href=\"spotify:artist:55Aa2cqylxrFIXC767Z865\">Lil Wayne</a>, <a href=\"spotify:artist:5pKCCKE2ajJHZ9KAiaK11H\">Rihanna</a>, and <a href=\"spotify:artist:13ubrt8QOOCPljQ2FL1Kca\">A$AP Rocky</a>. Thanks to his introspective rap style, his sensitive R&B crooning, and his gold-touch songwriting, each one of his albums -- from 2011's Take Care to 2018's Scorpion -- topped charts worldwide, and his singles, like the Grammy-winning \"Hotline Bling,\" and many mixtapes did too. As his star rose, he helped others along, sponsoring <a href=\"spotify:artist:1Xyo4u8uXC1ZmMpatF05PJ\">the Weeknd</a>'s early work, starting the <a href=\"spotify:search:label%3A%22OVO+Sound%22\">OVO Sound</a> label, and giving features on his records to up-and-coming acts. By the second decade of his career, Drake's constant chart domination, his Grammy wins and nominations, and his meme-worthy cultural presence made him one of the world's most popular musicians.     \r\n\nKnown initially for his role as Jimmy Brooks on Degrassi: The Next Generation, the Toronto-born Aubrey Drake Graham stepped out as a rapper and singer with pop appeal in 2006, when he initiated a series of mixtapes. A year later, despite being unsigned, he scored major exposure when his cocky and laid-back track \"Replacement Girl,\" featuring <a href=\"spotify:artist:2iojnBLj0qIMiKPvVhLnsH\">Trey Songz</a>, was featured on BET's 106 & Park program as its \"Joint of the Day.\" He raised his profile throughout the next several months by popping up on countless mixtapes and remixes, and as rumors swirled about contract offers from labels, he gradually became one of the most talked-about artists in the industry. It did not hurt that he had support from the likes of <a href=\"spotify:artist:5K4W6rqBFWDnAN6FQUkS6x\">Kanye West</a>, <a href=\"spotify:artist:3nFkdlSjzX9mRTtwJOzDYB\">Jay-Z</a>, and <a href=\"spotify:artist:55Aa2cqylxrFIXC767Z865\">Lil Wayne</a>. \r\n\nBy the end of June 2009, \"Best I Ever Had,\" a promotional single, had climbed to number two on Billboard's Hot R&B/Hip-Hop Songs chart. After a fierce bidding war, Drake signed with Universal Motown in late summer and released an EP, So Far Gone, made up of songs from his popular mixtape of the same title. It peaked at number six on the U.S. Billboard 200 chart and won a 2010 Juno Award for Rap Recording of the Year. Thank Me Later, a full-length featuring collaborations with the <a href=\"spotify:artist:2qk9voo8llSGYcZ6xrBzKx\">Kings of Leon</a>, <a href=\"spotify:artist:1W3FSF1BLpY3hlVIgvenLz\">the-Dream</a>, <a href=\"spotify:artist:3nFkdlSjzX9mRTtwJOzDYB\">Jay-Z</a>, <a href=\"spotify:artist:5K4W6rqBFWDnAN6FQUkS6x\">Kanye West</a>, and <a href=\"spotify:artist:55Aa2cqylxrFIXC767Z865\">Lil Wayne</a>, was issued through <a href=\"spotify:search:label%3A%22Young+Money%22\">Young Money</a> in June 2010. It debuted at number one on the U.S. Billboard 200 chart and was certified platinum by the Recording Industry Association of America. Still, the artist felt his debut was rushed, so its follow-up arrived in November 2015 with the title Take Care, referencing the increased time and effort put into the album's creation. Receiving critical acclaim, Grammy Awards, and the number one slot on the U.S. Billboard 200, Take Care cemented Drake's place as one of Canada's biggest exports. \r\n\nWhile on tour in 2012, Drake announced that he had started work on what would be his third studio album; Nothing Was the Same was released the following September. It spawned many singles, topped charts around the world, was shortlisted for the Polaris Music Prize, and was nominated for a Best Rap Album Grammy Award. Soon after the album's release, Drake hit the road on an extended tour, took part in some collaborations, and released a few singles, including the Grammy-nominated \"0 to 100/The Catch Up.\" His next release was planned as a free mixtape before <a href=\"spotify:search:label%3A%22Cash+Money%22\">Cash Money</a> decided they would rather charge for it. The decidedly downbeat If You're Reading This It's Too Late was released in February 2015 and debuted at number one, while all 17 of its songs entered the Hot R&B/Hip-Hop Songs chart. \r\n\nIn late summer 2015, he dropped a trio of new tracks on his SoundCloud page. One of them, the <a href=\"spotify:artist:7JLwBH0X2G8tgHceqvOu5B\">Timmy Thomas</a>-sampling \"Hotline Bling,\" became a Top Five pop hit in Canada and the U.S. and something of a cultural phenomenon. Later that year, Drake hit the studio with <a href=\"spotify:artist:1RyvyyTE3xzB2ZywiAwp0i\">Future</a> for a six-day session that yielded the mixtape What a Time to Be Alive. Upon the album's September release, it became Drake's second recording of the year to debut at number one. After dropping three singles in the beginning months of 2016, Drake's fourth album, Views, was released in April and debuted at number one. It revolved lyrically around his hometown of Toronto and featured production by longtime cohorts Noah \"40\" Shebib and Boi-1da, among others. Late that year, Drake issued another trio of singles, including the chart-topping \"Fake Love.\" They preceded the play list More Life, released the following March with appearances from <a href=\"spotify:artist:5K4W6rqBFWDnAN6FQUkS6x\">Kanye West</a>, <a href=\"spotify:artist:0VRj0yCOv2FXJNP47XQnx5\">Quavo</a>, <a href=\"spotify:artist:0Y5tJX1MQlPlqiwlOH1tJY\">Travis Scott</a>, and <a href=\"spotify:artist:50co4Is1HCEo8bhOyUWKpn\">Young Thug</a>. The release became his seventh consecutive chart-topping album.\r\n\nAt the start of 2018, Drake issued the two-song EP Scary Hours. Both \"Diplomatic Immunity\" and \"God's Plan\" hit the Top Ten, the latter becoming his second solo chart-topper. It served as a precursor to his fifth album, the two-disc set Scorpion, which was broken into a rap side and an R&B side that featured the hit single \"Nice for What.\" It was released in June and instantly went platinum, while also breaking records for most streams in a single day. At the 61st Grammy Awards, Drake took home the prize for Best Rap Song for \"God's Plan.\" \r\n\nIn 2019, Drake raided the vaults for two archival releases: an official streaming release of the So Far Gone mixtape, and the Billboard 200-topping Care Package, which rounded up tracks that were leaked, discarded, or used as teasers, dating back to the Take Care era. Drake collected two Grammy nominations for the 2020 ceremonies, one for best rap song with his <a href=\"spotify:artist:1sBkRIssrMs1AbVkOJbc7a\">Rick Ross</a> collaboration \"Gold Roses\" and another for best R&B song with his <a href=\"spotify:artist:7bXgB6jMjp9ATFy66eO08Z\">Chris Brown</a>-assisted \"No Guidance.\" That same year, he released another mixtape made up of demos and singles titled Dark Lane Demo Tapes. One of the songs was \"Toosie Slide,\" his third song to debut at number one on the Billboard Hot 100, making him the first male artist to accomplish that feat. ~ Andy Kellman & Tim Sendra, Rovi"
             },
             "externalLinks":{
                "items":[
                   
                ]
             }
          },
          "visuals":{
             "gallery":{
                "items":[
                   {
                      "sources":[
                         {
                            "url":"https://i.scdn.co/image/068ae749ee9825fcecc1a0f82ead09aaa8440228",
                            "width":640,
                            "height":638
                         }
                      ]
                   },
                   {
                      "sources":[
                         {
                            "url":"https://i.scdn.co/image/b9c34613d46da02ac6f213dcfe41a7ab9a0e27ef",
                            "width":640,
                            "height":427
                         }
                      ]
                   },
                   {
                      "sources":[
                         {
                            "url":"https://i.scdn.co/image/b3c1ceeedea2b62584b8a446c69d0846790cd068",
                            "width":640,
                            "height":641
                         }
                      ]
                   },
                   {
                      "sources":[
                         {
                            "url":"https://i.scdn.co/image/7fc3f93e4d9711af615bf58c0304a34094d985bd",
                            "width":640,
                            "height":510
                         }
                      ]
                   },
                   {
                      "sources":[
                         {
                            "url":"https://i.scdn.co/image/c9995bb765007e1a7f7f0cb0d7f5a1df010cf8c7",
                            "width":640,
                            "height":427
                         }
                      ]
                   },
                   {
                      "sources":[
                         {
                            "url":"https://i.scdn.co/image/871909ce6dca201d622507b5078bc1bd9ef2fbad",
                            "width":640,
                            "height":427
                         }
                      ]
                   },
                   {
                      "sources":[
                         {
                            "url":"https://i.scdn.co/image/381be1381235026fd7433b232ca04dc991eb9a94",
                            "width":640,
                            "height":366
                         }
                      ]
                   },
                   {
                      "sources":[
                         {
                            "url":"https://i.scdn.co/image/f68dd417b4f07e6c407fd55029a9bad0f0346ddf",
                            "width":640,
                            "height":640
                         }
                      ]
                   },
                   {
                      "sources":[
                         {
                            "url":"https://i.scdn.co/image/9843e3ab5a66858356afc4749ca606cc033912b9",
                            "width":640,
                            "height":427
                         }
                      ]
                   },
                   {
                      "sources":[
                         {
                            "url":"https://i.scdn.co/image/4efd9333646ec2e268f961595ef309653fb42bfd",
                            "width":640,
                            "height":371
                         }
                      ]
                   }
                ]
             },
             "avatarImage":{
                "sources":[
                   {
                      "url":"https://i.scdn.co/image/60cfab40c6bb160a1906be45276829d430058005",
                      "width":640,
                      "height":640
                   }
                ]
             },
             "headerImage":{
                "sources":[
                   {
                      "url":"https://i.scdn.co/image/a2ee94afb84f525ed12c58a60bf4d269b47b603a",
                      "width":2660,
                      "height":1140
                   }
                ]
             }
          }
       }
    }
 }