export const fm84Profile = {
    "data":{
       "artist":{
          "id":"1xvEo98zythSrgN69GQevk",
          "uri":"spotify:artist:1xvEo98zythSrgN69GQevk",
          "following":false,
          "sharingInfo":{
             "shareUrl":"https://open.spotify.com/artist/1xvEo98zythSrgN69GQevk?si=lVnq7J6GTpuX-rNlXHhAqg",
             "shareId":"lVnq7J6GTpuX-rNlXHhAqg"
          },
          "profile":{
             "name":"FM-84",
             "verified":true,
             "pinnedItem":null,
             "biography":{
                "text":"FM-84 is Col Bennett, a music producer from Ayrshire, Scotland - currently based in San Francisco, California.\n\nAfter a sold out tour of the US and Canada in 2018 and an epic fourteen date tour of the US, Canada and UK (London) in 2019, both with lead collaborator <a href=\"spotify:artist:1anhHn744LbctzF9EHpvea\" data-name=\"Ollie Wride\">Ollie Wride</a>, Col is taking time out to work on the highly anticipated follow-up to Atlas.\n\nThe tours follow the independent success of “Atlas”, the debut album from FM-84. Vehlinggo described the album as “Stunning. Stratospheric and Enchanting.” NewRetroWave said “Atlas is a profound masterpiece of an album done with an almost unfathomable attention to detail.” and Magnetic Magazine called it “Incredible. An album that rattles you so intensely to the core that you can’t believe what you’re hearing.”\n\n&#34;Atlas&#34; is the story of wonder, imagination, dreams, youth, innocence, love and heartbreak all captured under the golden light of a fading summer sun. The sound of a summer long gone.\n\nOfficial Merch Store (T-Shirts, CDs and Cassettes)\nhttp://smarturl.it/fm84\n\nOfficial FM-84 YouTube Channel\nhttps://youtube.com/c/fm84official\n\nContact FM-84\nhello&#64;fm84.com\n\nUnited Talent Agency (Worldwide Bookings)\nfm84team&#64;unitedtalent.com\n\nPhotograph by Marco Bicca\nIllustration by Felipe Protski Martins\n"
             },
             "externalLinks":{
                "items":[
                   {
                      "name":"FACEBOOK",
                      "url":"https://facebook.com/fm84music"
                   },
                   {
                      "name":"INSTAGRAM",
                      "url":"https://instagram.com/fm84music"
                   },
                   {
                      "name":"TWITTER",
                      "url":"https://twitter.com/fm84"
                   }
                ]
             }
          },
          "visuals":{
             "gallery":{
                "items":[
                   {
                      "sources":[
                         {
                            "url":"https://i.scdn.co/image/b23d206e17b191180d38b9a25c122032e7fa0ac5",
                            "width":640,
                            "height":640
                         }
                      ]
                   }
                ]
             },
             "avatarImage":{
                "sources":[
                   {
                      "url":"https://i.scdn.co/image/2ba7564069de0b3c9830b66146d36eba69f2cd0d",
                      "width":640,
                      "height":640
                   }
                ]
             },
             "headerImage":{
                "sources":[
                   {
                      "url":"https://i.scdn.co/image/9241ae4bb77936a9eaa5e49892a2595da67292a6",
                      "width":2660,
                      "height":1140
                   }
                ]
             }
          }
       }
    }
 }