export const LilTjayProfile = {
    "data":{
       "artist":{
          "id":"6jGMq4yGs7aQzuGsMgVgZR",
          "uri":"spotify:artist:6jGMq4yGs7aQzuGsMgVgZR",
          "following":false,
          "sharingInfo":{
             "shareUrl":"https://open.spotify.com/artist/6jGMq4yGs7aQzuGsMgVgZR?si=69A1KVcVRSSL7E2IJ7aurA",
             "shareId":"69A1KVcVRSSL7E2IJ7aurA"
          },
          "profile":{
             "name":"Lil Tjay",
             "verified":true,
             "pinnedItem":null,
             "biography":{
                "text":"Before Lil TJay became the Internet heartthrob with delectable deliveries and streams in the multi-millions, he was just a kid from the Bronx with an equal love for Jay-Z bars and Justin Bieber songs. His mother’s favorite artists (Usher, Michael Jackson) taught him melody. Today, that melody is the 17-year-old’s gift as well as a catalyst for his embryonic hip-hop stardom. To hear the rhyme rookie’s early succession of rap hits is to experience aqua flows and stark hooks as addictive as Instagram’s discovery page. A closer listen offers the biography of a kid who survived adult sins and consequences before he was old enough to drive.  \n \nRaised in an NYC neighborhood saturated with gang culture and deficient of positivity, Lil TJay eventually earned himself a year of incarceration. Upon release, he committed himself to finding legal routes toward his music dreams. The studio would be his saving grace and destiny. His first recording birthed the heartless yet catchy “Resume.” Soon after, the flammable “Brothers” would earn him his first Internet smash. The infectious hook and sophisticated harmony snatched ears and eyes to the tune of 27 million plus YouTube viewers. The follow-up, “None of your Love” exhibited TJay’s artistic range as it swam into deeper R&amp;B waters to express a Pitbull’s puppy love. It’s as if Jackson 5 MJ and Future turnt up in some alternate universe.\n "
             },
             "externalLinks":{
                "items":[
                   {
                      "name":"INSTAGRAM",
                      "url":"https://instagram.com/liltjay"
                   },
                   {
                      "name":"TWITTER",
                      "url":"https://twitter.com/liltjay"
                   }
                ]
             }
          },
          "visuals":{
             "gallery":{
                "items":[
                   {
                      "sources":[
                         {
                            "url":"https://i.scdn.co/image/d2d4c353b74cf2734507d98229a5b52f4872e2c5",
                            "width":640,
                            "height":640
                         }
                      ]
                   }
                ]
             },
             "avatarImage":{
                "sources":[
                   {
                      "url":"https://i.scdn.co/image/db9945fd5985316262acb98c17b0a15ed5a65c8c",
                      "width":640,
                      "height":640
                   }
                ]
             },
             "headerImage":{
                "sources":[
                   {
                      "url":"https://i.scdn.co/image/e2612d062176f49bfc64e47881a74eb6fe249619",
                      "width":2660,
                      "height":1140
                   }
                ]
             }
          }
       }
    }
 }