export const WeekndProfile = {
    "data":{
       "artist":{
          "id":"1Xyo4u8uXC1ZmMpatF05PJ",
          "uri":"spotify:artist:1Xyo4u8uXC1ZmMpatF05PJ",
          "following":false,
          "sharingInfo":{
             "shareUrl":"https://open.spotify.com/artist/1Xyo4u8uXC1ZmMpatF05PJ?si=nrxeihdOTXKJPIAyOvRAuQ",
             "shareId":"nrxeihdOTXKJPIAyOvRAuQ"
          },
          "profile":{
             "name":"The Weeknd",
             "verified":true,
             "pinnedItem":null,
             "biography":{
                "text":"The Weeknd took over pop music &amp; culture on his own terms filtering R&amp;B, Pop,&amp; hip-hop through an ambitious widescreen lens. The multi-platinum 3X GRAMMY Award winner has emerged as one of the most successful &amp; significant artists of the modern era. 2012’s 3X platinum <a href=\"spotify:album:5EbpxRwbbpCJUepbqVTZ1U\" data-name=\"Trilogy\">Trilogy</a> collated 3 breakout mixtapes—House of Balloons, Thursday &amp; Echoes of Silence—into his 1st chart-topping collection followed by his debut LP <a href=\"spotify:album:3hhDpPtCFuQbppwYgsVhMO\" data-name=\"Kiss Land\">Kiss Land</a> in 2013. Two years later, “Earned It (Fifty Shades of Grey)” won “Best R&amp;B Performance” &amp; received an Academy Award nod for “Best Original Song” &amp; 4X Platinum  <a href=\"spotify:album:0P3oVJBFOv3TDXlYRhGL7s\" data-name=\"Beauty Behind The Madness\">Beauty Behind The Madness</a> won a GRAMMY for “Best Urban Contemporary Album.”  In 2018, <a href=\"spotify:album:2ODvWsOgouMbaA5xf0RkJe\" data-name=\"Starboy\">Starboy</a> won the same award, making him the 1st artist ever to win twice. His 6-track project My Dear Melancholy marked his 3rd consecutive #1 bow on the Billboard Top 200, &amp; “Pray For Me” with Kendrick Lamar was featured in the trailer for the Academy Award winning Marvel film Black Panther. In 2020 the 80’s-nostalgic track <a href=\"spotify:track:0VjIjW4GlUZAMYd2vXMi3b\" data-name=\"Blinding Lights\">Blinding Lights</a> became a worldwide sensation, igniting viral dance challenges across social media, peaking at #1 in 30+ countries &amp; headlining Mercedes Benz EQC campaign. <a href=\"spotify:album:4yP0hdKOZPNshxUOjY0cZj\" data-name=\"After Hours\">After Hours</a> held the #1 spot on Billboard 200 for 4 consecutive weeks, marking his 4th #1 album &amp; becoming the first to ever rank #1 on the Billboard 200, Hot 100, and Artist 100 simultaneously.  <a href=\"spotify:album:4yP0hdKOZPNshxUOjY0cZj\" data-name=\"After Hours\">After Hours</a> is the #1 R&amp;B streaming album of all time (followed by <a href=\"spotify:album:2ODvWsOgouMbaA5xf0RkJe\" data-name=\"Starboy\">Starboy</a> at #2).  \n"
             },
             "externalLinks":{
                "items":[
                   {
                      "name":"FACEBOOK",
                      "url":"https://facebook.com/theweeknd/"
                   },
                   {
                      "name":"INSTAGRAM",
                      "url":"https://instagram.com/theweeknd/?hl=en"
                   },
                   {
                      "name":"TWITTER",
                      "url":"https://twitter.com/theweeknd?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor"
                   },
                   {
                      "name":"WIKIPEDIA",
                      "url":"https://en.wikipedia.org/wiki/The_Weeknd"
                   }
                ]
             }
          },
          "visuals":{
             "gallery":{
                "items":[
                   {
                      "sources":[
                         {
                            "url":"https://i.scdn.co/image/c0b93a8b0cedd2ad1c325da4146f57fa9b9ff2e1",
                            "width":640,
                            "height":640
                         }
                      ]
                   },
                   {
                      "sources":[
                         {
                            "url":"https://i.scdn.co/image/c2f6098ae1c39735561c7863c0f3b09f0ef40f93",
                            "width":640,
                            "height":640
                         }
                      ]
                   },
                   {
                      "sources":[
                         {
                            "url":"https://i.scdn.co/image/b5302ce2f05526c41b22afab9fc6b56701c53b83",
                            "width":640,
                            "height":640
                         }
                      ]
                   },
                   {
                      "sources":[
                         {
                            "url":"https://i.scdn.co/image/fbfc83b25e4e95338b4977c02ec48ec0412edb10",
                            "width":640,
                            "height":640
                         }
                      ]
                   }
                ]
             },
             "avatarImage":{
                "sources":[
                   {
                      "url":"https://i.scdn.co/image/d9a875c37277c35b94c60c00d2cd256db098505d",
                      "width":640,
                      "height":640
                   }
                ]
             },
             "headerImage":{
                "sources":[
                   {
                      "url":"https://i.scdn.co/image/5cf62c6c908c0a211c0a6eb5ea1878b17df5b9bb",
                      "width":2660,
                      "height":1140
                   }
                ]
             }
          }
       }
    }
 }